/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/program-1rm-test`; params?: Router.UnknownInputParams; } | { pathname: `/whoop-callback`; params?: Router.UnknownInputParams; } | { pathname: `/workout-session`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/nutrition` | `/nutrition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/programs` | `/programs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/whoop` | `/whoop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/workouts` | `/workouts`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition/chat`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/program-1rm-test`; params?: Router.UnknownOutputParams; } | { pathname: `/whoop-callback`; params?: Router.UnknownOutputParams; } | { pathname: `/workout-session`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/nutrition` | `/nutrition`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/programs` | `/programs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/whoop` | `/whoop`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/workouts` | `/workouts`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/nutrition/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/nutrition`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/program-1rm-test${`?${string}` | `#${string}` | ''}` | `/whoop-callback${`?${string}` | `#${string}` | ''}` | `/workout-session${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/nutrition${`?${string}` | `#${string}` | ''}` | `/nutrition${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/programs${`?${string}` | `#${string}` | ''}` | `/programs${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/whoop${`?${string}` | `#${string}` | ''}` | `/whoop${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/workouts${`?${string}` | `#${string}` | ''}` | `/workouts${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/sign-up${`?${string}` | `#${string}` | ''}` | `/nutrition/chat${`?${string}` | `#${string}` | ''}` | `/nutrition${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/program-1rm-test`; params?: Router.UnknownInputParams; } | { pathname: `/whoop-callback`; params?: Router.UnknownInputParams; } | { pathname: `/workout-session`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/nutrition` | `/nutrition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/programs` | `/programs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/whoop` | `/whoop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/workouts` | `/workouts`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition/chat`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition`; params?: Router.UnknownInputParams; };
    }
  }
}
