CREATE INDEX `idx_exercises_user_id_updated_at` ON `exercises` (`user_id`, `updated_at`);
CREATE INDEX `idx_exercises_muscle_group` ON `exercises` (`muscle_group`);
CREATE INDEX `idx_templates_user_id_updated_at` ON `templates` (`user_id`, `updated_at`);
CREATE INDEX `idx_workouts_user_id_started_at` ON `workouts` (`user_id`, `started_at`);
CREATE INDEX `idx_workouts_template_id` ON `workouts` (`template_id`);
CREATE INDEX `idx_workouts_completed_at` ON `workouts` (`completed_at`);
CREATE INDEX `idx_workout_exercises_order` ON `workout_exercises` (`workout_id`, `order_index`);
CREATE INDEX `idx_workout_exercises_exercise_id` ON `workout_exercises` (`exercise_id`);
CREATE INDEX `idx_workout_sets_workout_exercise_id` ON `workout_sets` (`workout_exercise_id`);
CREATE INDEX `idx_workout_sets_completed_at` ON `workout_sets` (`completed_at`);
CREATE INDEX `idx_user_program_cycles_user_id` ON `user_program_cycles` (`user_id`);
CREATE INDEX `idx_program_cycle_workouts_cycle_id` ON `program_cycle_workouts` (`cycle_id`);
CREATE INDEX `idx_program_cycle_workouts_scheduled_at` ON `program_cycle_workouts` (`scheduled_at`);
CREATE INDEX `idx_template_exercises_template_id` ON `template_exercises` (`template_id`);
CREATE INDEX `idx_user_integration_user_id` ON `user_integration` (`user_id`);
CREATE INDEX `idx_user_integration_provider` ON `user_integration` (`provider`);
CREATE INDEX `idx_user_integration_user_id_provider` ON `user_integration` (`user_id`, `provider`);
CREATE INDEX `idx_whoop_profile_user_id` ON `whoop_profile` (`user_id`);
CREATE INDEX `idx_whoop_profile_whoop_user_id` ON `whoop_profile` (`whoop_user_id`);
CREATE INDEX `idx_whoop_workout_user_id` ON `whoop_workout` (`user_id`);
CREATE INDEX `idx_whoop_workout_whoop_workout_id` ON `whoop_workout` (`whoop_workout_id`);
CREATE INDEX `idx_whoop_workout_start` ON `whoop_workout` (`start`);
CREATE INDEX `idx_whoop_workout_user_id_start` ON `whoop_workout` (`user_id`, `start`);
CREATE INDEX `idx_whoop_recovery_user_id` ON `whoop_recovery` (`user_id`);
CREATE INDEX `idx_whoop_recovery_whoop_recovery_id` ON `whoop_recovery` (`whoop_recovery_id`);
CREATE INDEX `idx_whoop_recovery_date` ON `whoop_recovery` (`date`);
CREATE INDEX `idx_whoop_recovery_user_id_date` ON `whoop_recovery` (`user_id`, `date`);
CREATE INDEX `idx_whoop_recovery_cycle_id` ON `whoop_recovery` (`cycle_id`);
CREATE INDEX `idx_whoop_cycle_user_id` ON `whoop_cycle` (`user_id`);
CREATE INDEX `idx_whoop_cycle_whoop_cycle_id` ON `whoop_cycle` (`whoop_cycle_id`);
CREATE INDEX `idx_whoop_cycle_start` ON `whoop_cycle` (`start`);
CREATE INDEX `idx_whoop_cycle_user_id_start` ON `whoop_cycle` (`user_id`, `start`);
CREATE INDEX `idx_whoop_cycle_day_strain` ON `whoop_cycle` (`day_strain`);
CREATE INDEX `idx_whoop_sleep_user_id` ON `whoop_sleep` (`user_id`);
CREATE INDEX `idx_whoop_sleep_whoop_sleep_id` ON `whoop_sleep` (`whoop_sleep_id`);
CREATE INDEX `idx_whoop_sleep_start` ON `whoop_sleep` (`start`);
CREATE INDEX `idx_whoop_sleep_user_id_start` ON `whoop_sleep` (`user_id`, `start`);
CREATE INDEX `idx_whoop_sleep_user_id_sleep_performance` ON `whoop_sleep` (`user_id`, `sleep_performance_percentage`);
CREATE INDEX `idx_whoop_body_measurement_user_id` ON `whoop_body_measurement` (`user_id`);
CREATE INDEX `idx_whoop_body_measurement_whoop_measurement_id` ON `whoop_body_measurement` (`whoop_measurement_id`);
CREATE INDEX `idx_whoop_body_measurement_measurement_date` ON `whoop_body_measurement` (`measurement_date`);
CREATE INDEX `idx_whoop_body_measurement_user_id_measurement_date` ON `whoop_body_measurement` (`user_id`, `measurement_date`);
CREATE INDEX `idx_rate_limit_user_id_endpoint` ON `rate_limit` (`user_id`, `endpoint`);
CREATE INDEX `idx_rate_limit_window_start` ON `rate_limit` (`window_start`);
CREATE INDEX `idx_nutrition_entries_user_logged_at` ON `nutrition_entries` (`user_id`, `logged_at`);
CREATE INDEX `idx_nutrition_entries_user_deleted` ON `nutrition_entries` (`user_id`, `is_deleted`);
CREATE INDEX `idx_user_body_stats_user` ON `user_body_stats` (`user_id`);
