export const defaultTemplates = [
  {
    name: 'Push Day',
    description: 'Chest, Shoulders, Triceps',
    notes: 'Primary pushing muscles - aim for progressive overload',
    exercises: [
      {
        exerciseId: 'bench-press',
        sets: 4,
        reps: 8,
        isAmrap: false,
        isAccessory: false,
        isRequired: true,
        orderIndex: 0,
      },
      {
        exerciseId: 'incline-dumbbell-press',
        sets: 4,
        reps: 10,
        isAmrap: false,
        isAccessory: false,
        isRequired: true,
        orderIndex: 1,
      },
      {
        exerciseId: 'overhead-press',
        sets: 4,
        reps: 8,
        isAmrap: false,
        isAccessory: false,
        isRequired: true,
        orderIndex: 2,
      },
      {
        exerciseId: 'lateral-raises',
        sets: 3,
        reps: 12,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 3,
      },
      {
        exerciseId: 'tricep-pushdown',
        sets: 3,
        reps: 12,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 4,
      },
    ],
  },
  {
    name: 'Pull Day',
    description: 'Back, Biceps',
    notes: 'Primary pulling muscles - focus on mind-muscle connection',
    exercises: [
      {
        exerciseId: 'barbell-row',
        sets: 4,
        reps: 8,
        isAmrap: false,
        isAccessory: false,
        isRequired: true,
        orderIndex: 0,
      },
      {
        exerciseId: 'pull-ups',
        sets: 4,
        reps: 8,
        isAmrap: false,
        isAccessory: false,
        isRequired: true,
        orderIndex: 1,
      },
      {
        exerciseId: 'lat-pulldown',
        sets: 3,
        reps: 10,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 2,
      },
      {
        exerciseId: 'face-pulls',
        sets: 3,
        reps: 15,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 3,
      },
      {
        exerciseId: 'barbell-curl',
        sets: 3,
        reps: 10,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 4,
      },
    ],
  },
  {
    name: 'Leg Day',
    description: 'Quads, Hamstrings, Calves',
    notes: 'Lower body - warm up thoroughly',
    exercises: [
      {
        exerciseId: 'squat',
        sets: 4,
        reps: 6,
        isAmrap: false,
        isAccessory: false,
        isRequired: true,
        orderIndex: 0,
      },
      {
        exerciseId: 'romanian-deadlift',
        sets: 4,
        reps: 8,
        isAmrap: false,
        isAccessory: false,
        isRequired: true,
        orderIndex: 1,
      },
      {
        exerciseId: 'leg-press',
        sets: 3,
        reps: 10,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 2,
      },
      {
        exerciseId: 'leg-curl',
        sets: 3,
        reps: 12,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 3,
      },
      {
        exerciseId: 'standing-calf-raise',
        sets: 4,
        reps: 12,
        isAmrap: false,
        isAccessory: true,
        isRequired: false,
        orderIndex: 4,
      },
    ],
  },
];
