import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

type InfisicalEnv = 'dev' | 'staging' | 'prod';

const envName = process.argv[2] as InfisicalEnv | undefined;
const allowedEnvs = new Set<InfisicalEnv>(['dev', 'staging', 'prod']);
const envFile = join(process.cwd(), '.env.local');

if (!envName || !allowedEnvs.has(envName)) {
  console.error('Usage: bun run scripts/sync-expo-env.ts <dev|staging|prod>');
  process.exit(1);
}

const result = spawnSync(
  'infisical',
  [
    'run',
    `--env=${envName}`,
    '--project-config-dir',
    '../..',
    '--',
    'node',
    '-e',
    `
const publicEnv = {};
for (const [key, value] of Object.entries(process.env)) {
  if (key.startsWith('EXPO_PUBLIC_') && value) {
    publicEnv[key] = value;
  }
}
if (!publicEnv.EXPO_PUBLIC_APP_SCHEME) {
  publicEnv.EXPO_PUBLIC_APP_SCHEME = 'strength';
}
if (!publicEnv.EXPO_PUBLIC_WORKER_BASE_URL) {
  console.error('Missing required Infisical secret: EXPO_PUBLIC_WORKER_BASE_URL');
  process.exit(1);
}
console.log(JSON.stringify(publicEnv));
`,
  ],
  {
    cwd: process.cwd(),
    encoding: 'utf-8',
  },
);

if (result.status !== 0) {
  console.error(
    result.stderr.trim() || `Unable to read Expo public env from Infisical ${envName}.`,
  );
  console.error(
    'Run `infisical login` and confirm `.infisical.json` points at the strength project.',
  );
  process.exit(result.status ?? 1);
}

let publicEnv: Record<string, string>;

try {
  publicEnv = JSON.parse(result.stdout.trim()) as Record<string, string>;
} catch {
  console.error('Unable to parse Infisical env output.');
  console.error(result.stdout.trim());
  process.exit(1);
}

if (envName === 'staging' || envName === 'prod') {
  try {
    const url = new URL(publicEnv.EXPO_PUBLIC_WORKER_BASE_URL);
    if (url.protocol !== 'https:') {
      throw new Error('must start with https://');
    }
  } catch (error) {
    console.error(
      `Invalid EXPO_PUBLIC_WORKER_BASE_URL for ${envName}: ${publicEnv.EXPO_PUBLIC_WORKER_BASE_URL}`,
    );
    console.error(
      error instanceof Error ? error.message : `Expected a valid ${envName} Worker URL.`,
    );
    process.exit(1);
  }
}

const content = [
  `# Generated by bun run sync-env:${envName}`,
  `# Source: Infisical ${envName}`,
  ...Object.entries(publicEnv)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `${key}=${value}`),
  '',
].join('\n');

writeFileSync(envFile, content);

console.log(`Wrote ${Object.keys(publicEnv).length} EXPO_PUBLIC_* vars to ${envFile}`);
console.log(`EXPO_PUBLIC_WORKER_BASE_URL=${publicEnv.EXPO_PUBLIC_WORKER_BASE_URL}`);
